### ISSUE TITLE
crashed by malloc(): unaligned fastbin chunk detected 3

### ISSUE THREAD

**Issue by buzztaiki** [buzztaiki/ponde#5]
It was worked until recently, why...

```console
$ gdb -q --args ./target/debug/ponde config.yaml
Reading symbols from ./target/debug/ponde...
warning: Missing auto-load script at offset 0 in section .debug_gdb_scripts
of file /home/taiki/dev/src/github.com/buzztaiki/ponde/target/debug/ponde.
Use `info auto-load python-scripts [REGEXP]' to list them.
(gdb) run
Starting program: /home/taiki/dev/src/github.com/buzztaiki/ponde/target/debug/ponde config.yaml
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/usr/lib/libthread_db.so.1".
malloc(): unaligned fastbin chunk detected 3

Program received signal SIGABRT, Aborted.
0x00007ffff7d3734c in __pthread_kill_implementation () from /usr/lib/libc.so.6
(gdb) bt
#0  0x00007ffff7d3734c in __pthread_kill_implementation () at /usr/lib/libc.so.6
#1  0x00007ffff7cea4b8 in raise () at /usr/lib/libc.so.6
#2  0x00007ffff7cd4534 in abort () at /usr/lib/libc.so.6
#3  0x00007ffff7d2b397 in __libc_message () at /usr/lib/libc.so.6
#4  0x00007ffff7d4133c in  () at /usr/lib/libc.so.6
#5  0x00007ffff7d447ec in _int_malloc () at /usr/lib/libc.so.6
#6  0x00007ffff7d45752 in malloc () at /usr/lib/libc.so.6
#7  0x00007ffff7d480d0 in strdup () at /usr/lib/libc.so.6
#8  0x00007ffff7f27631 in  () at /usr/lib/libudev.so.1
#9  0x00007ffff7f2e07e in  () at /usr/lib/libudev.so.1
#10 0x00007ffff7f2e206 in  () at /usr/lib/libudev.so.1
#11 0x00007ffff7f31d3f in  () at /usr/lib/libudev.so.1
#12 0x00007ffff7f3245f in udev_monitor_receive_device () at /usr/lib/libudev.so.1
#13 0x00007ffff7f04db9 in  () at /usr/lib/libinput.so.10
#14 0x00007ffff7edcde7 in libinput_dispatch () at /usr/lib/libinput.so.10
#15 0x00005555556276df in input::context::Libinput::dispatch (self=0x7fffffffdd48) at /home/taiki/.cargo/registry/src/github.com-1ecc6299db9ec823/input-0.7.0/src/context.rs:333
#16 0x00005555555936bc in ponde::app::App::event_loop (self=0x7fffffffe138) at src/app.rs:42
#17 0x00005555555b3225 in ponde::main () at src/main.rs:30
```

**Comment by buzztaiki** [comment]
it was also reproduced by following patch:

```diff
diff --git a/src/app.rs b/src/app.rs
index fec1473..adefbf7 100644
--- a/src/app.rs
+++ b/src/app.rs
@@ -53,36 +53,15 @@ impl<'a> App<'a> {
     }
 
     fn handle_event(&mut self, event: &Event) -> Result<(), Error> {
-        let mut device = event.device();
-        let device_config = match self.config.matched_device(&(&device).into()) {
-            Some(x) => x,
-            None => return Ok(()),
-        };
-
+        let device = event.device();
+        eprintln!("event: {:?}", event);
         match event {
             Event::Device(DeviceEvent::Added(_)) => {
                 let udev_device = udev_device(&device)
                     .ok_or_else(|| Error::Error("failed to get udev_device".to_string()))?;
-
-                let devnode = udev_device
-                    .devnode()
-                    .ok_or_else(|| Error::Error("failed to get devnode".to_string()))?;
-
-                device_config.apply_to(&mut device)?;
-
-                {
-                    let mut map = self.device_fd_map.lock().unwrap();
-                    let device_fd = map.get_by_path_mut(devnode).ok_or_else(|| {
-                        Error::Error(format!("failed to get device_fd of {}", devnode.display()))
-                    })?;
-                    device_fd.grab()?;
-                }
-            }
-            Event::Pointer(ev) => {
-                let sink_event = SinkEvent::from_pointer_event(ev, device_config)?;
-                self.sink_device.send_event(&sink_event)?;
+                eprintln!("udev_device: {:?}, {:?}", udev_device.devnode(), udev_device.sysname());
             }
-            _ => return Err(Error::Error(format!("unexpected event: {:?}", event))),
+            _ => (),
         }
         Ok(())
     }
```

**Comment by buzztaiki** [comment]
and following patch was not reproduce this issue:

```diff
diff --git a/src/app.rs b/src/app.rs
index fec1473..e5650eb 100644
--- a/src/app.rs
+++ b/src/app.rs
@@ -53,36 +53,13 @@ impl<'a> App<'a> {
     }
 
     fn handle_event(&mut self, event: &Event) -> Result<(), Error> {
-        let mut device = event.device();
-        let device_config = match self.config.matched_device(&(&device).into()) {
-            Some(x) => x,
-            None => return Ok(()),
-        };
-
+        let device = event.device();
+        eprintln!("event: {:?}", event);
         match event {
             Event::Device(DeviceEvent::Added(_)) => {
-                let udev_device = udev_device(&device)
-                    .ok_or_else(|| Error::Error("failed to get udev_device".to_string()))?;
-
-                let devnode = udev_device
-                    .devnode()
-                    .ok_or_else(|| Error::Error("failed to get devnode".to_string()))?;
-
-                device_config.apply_to(&mut device)?;
-
-                {
-                    let mut map = self.device_fd_map.lock().unwrap();
-                    let device_fd = map.get_by_path_mut(devnode).ok_or_else(|| {
-                        Error::Error(format!("failed to get device_fd of {}", devnode.display()))
-                    })?;
-                    device_fd.grab()?;
-                }
-            }
-            Event::Pointer(ev) => {
-                let sink_event = SinkEvent::from_pointer_event(ev, device_config)?;
-                self.sink_device.send_event(&sink_event)?;
+                eprintln!("added: {:?}, {:?}", device.name(), device.sysname());
             }
-            _ => return Err(Error::Error(format!("unexpected event: {:?}", event))),
+            _ => (),
         }
         Ok(())
     }
```

**Comment by buzztaiki** [comment]
smallest reproducible code:

```rust
use std::os::unix::prelude::*;
use std::path::Path;

use evdev::uinput::VirtualDeviceBuilder;
use input::event::EventTrait;
use input::{Libinput, LibinputInterface};
use nix::fcntl::{open, OFlag};
use nix::sys::stat::Mode;
use nix::unistd::close;

pub struct Interface;
impl LibinputInterface for Interface {
    fn open_restricted(&mut self, path: &Path, flags: i32) -> Result<RawFd, i32> {
        open(path, OFlag::from_bits_truncate(flags), Mode::empty()).map_err(|e| e as i32)
    }
    fn close_restricted(&mut self, fd: RawFd) {
        if let Err(e) = close(fd) {
            eprintln!("failed to close {}: {}", fd, e);
        }
    }
}

fn main() -> anyhow::Result<()> {
    let _vdevice = VirtualDeviceBuilder::new()?.name("vdevice").build()?;

    let mut input = Libinput::new_with_udev(Interface);
    input.udev_assign_seat("seat0").unwrap();
    loop {
        input.dispatch().unwrap();
        for event in &mut input {
            match event {
                input::Event::Device(input::event::DeviceEvent::Added(_)) => {
                    let device = event.device();
                    eprintln!("added device: {}, {}", device.name(), device.sysname());
                    let _udev_device = unsafe { device.udev_device() };
                }
                _ => eprintln!("event {:?}", event),
            }
        }
    }
}
```
